[tool.poetry]
name = "annotation"
version = "0.1.0"
description = "Annotation microservice for BadgerDoc project"
authors = ["BadgerDoc team"]

[tool.poetry.dependencies]
python = "~3.12.1"
fastapi = "0.108.0"
uvicorn = "0.25.0"
SQLAlchemy = "2.0.23"
psycopg2-binary = "2.9.9"
alembic = "1.13.1"
python-dotenv = "1.0.0"
PyYAML = "6.0.1"
boto3 = "1.34.9"
requests = "2.31.0"
cryptography = "41.0.7"
cachetools = "5.3.2"
kafka-python = "2.0.2"
sqlalchemy-utils = "0.41.1"
lru-dict = "1.3.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.0"
commitizen = "3.13.0"
black = "23.12.1"
isort = "5.13.2"
pylint = "3.0.3"
pytest = "7.4.3"
pytest-cov = "4.1.0"
responses = "0.24.1"
moto = {extras = ["s3"], version = "4.2.12"}
click = "8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
